### ISSUE TITLE
Example config question

### ISSUE THREAD

**Issue by x-Felix** [madnuttah/unbound-docker#78]
I am taking this [example config](https://raw.githubusercontent.com/madnuttah/unbound-docker/refs/heads/main/doc/examples/docker-compose-madnuttah.yaml) as reference to add Redis cache for unbound. 
Curious of the docket networks assignment in the docker compose config.

`pihole` container has two networks (`docker`, `docker-bridge`) attached. 
`unbound` container has only `docker` network attached. 
`unbound-db-socket` and `unbound-db` are all in `docker-bridge` network. 

Suppose pihole only needs to talk to unbound, why does it need docker-bridge network? 
unbound suppose having dependence on unbound-db-socket and unbound-db, but they are in different networks, how they communicate? 

I haven't tested the example config in my home production environment. Just want to make sure I fully understand the settings before pulling the trigger. 

Thanks.

**Comment by madnuttah** [comment]
Hey @x-Felix and thanks for reaching out!

That's pretty much the compose file I'm using. I prefer a `macvlan` configuration and the issue is that the host can't communicate with the pi-hole container (and vice versa, of course), which is needed for the host's dns lookups in that case. To circumvent this, a separate bridge network was attached to pi-hole. I don't allow access to unbound from any device but pi-hole, so a pure `macvlan` config is sufficient.

The networks for the unbound-db and unbound-db-socket ain't really needed.

In case you ask yourself, >>why `macvlan`<<? I have firewall rules.

Cheers!
